# vim:set ft=dockerfile:
FROM ruby:2.3.5-alpine

MAINTAINER Alex Ouzounis <alex.ouzounis@solarwinds.com>

ENV NOKOGIRI_USE_SYSTEM_LIBRARIES=1

RUN \
    apk add --update \
      ruby-bigdecimal \
      ruby-bundler \
      ruby-rdoc \
      build-base \
      ruby-dev \
      git \
      openssh \
      ca-certificates \
    \
    && bundle config build.nokogiri --use-system-libraries \
    \
    && rm -rf /var/cache/apk/* /tmp
